"""
validate_schema.py — Validate the final analysis JSON output.

Checks:
  1. Required top-level fields present
  2. No em-dashes (—) or smart quotes (''"") in string fields
  3. Ingredient cal-sums within ±2 of meal calories (if mealPlan present)
  4. Entries array structure
  5. Totals structure

NO LLM calls. Pure Python / stdlib regex.
"""

from __future__ import annotations
import json
import re

# Em-dash and smart quote characters
_BAD_CHARS_RE = re.compile(r'[—‘’“”]')

_REQUIRED_TOP_LEVEL = ("date", "entries", "totals")


def validate(output: dict) -> tuple[bool, list[str]]:
    """Validate full analysis output dict.

    Returns:
        (ok, violations) where ok is False if any violations found.
    """
    violations: list[str] = []

    if not isinstance(output, dict):
        return False, ["output is not a dict"]

    # Check required fields
    for field in _REQUIRED_TOP_LEVEL:
        if field not in output:
            violations.append(f"missing required field: {field}")

    # Check for em-dashes and smart quotes ONLY in orchestrator-generated content.
    # Skip pwaProfile (echoed through from canonical profile files which may legitimately
    # contain em-dashes in user-authored notes) and goals._resolved (same — pass-through
    # from profile via Goals.resolve). These are not regenerated by the LLM each run.
    _GENERATED_FIELDS = ("highlights", "concerns", "coachResponses", "mealPlan", "regimen", "weight")
    for field in _GENERATED_FIELDS:
        if field in output:
            _scan_for_bad_chars(output[field], path=field, violations=violations)
    # Also scan entries (each entry's description and notes are generated by the entry analyzer)
    if "entries" in output and isinstance(output["entries"], list):
        for i, entry in enumerate(output["entries"]):
            for sub in ("description", "notes"):
                if sub in entry:
                    _scan_for_bad_chars(entry[sub], path=f"entries[{i}].{sub}", violations=violations)

    # Check ingredient cal sums if mealPlan present
    meal_plan = output.get("mealPlan")
    if meal_plan and isinstance(meal_plan, dict):
        _validate_meal_plan(meal_plan, violations)

    # Check totals structure
    totals = output.get("totals")
    if totals is not None:
        if not isinstance(totals, dict):
            violations.append("totals must be a dict")
        else:
            for field in ("calories", "protein"):
                if field not in totals:
                    violations.append(f"totals missing field: {field}")

    # Check entries
    entries = output.get("entries")
    if entries is not None:
        if not isinstance(entries, list):
            violations.append("entries must be a list")
        else:
            for i, entry in enumerate(entries):
                if not isinstance(entry, dict):
                    violations.append(f"entries[{i}] is not a dict")
                elif "id" not in entry:
                    violations.append(f"entries[{i}] missing id field")

    ok = len(violations) == 0
    return ok, violations


def _scan_for_bad_chars(obj: object, path: str, violations: list[str]) -> None:
    """Recursively scan all string values for em-dashes and smart quotes."""
    if isinstance(obj, str):
        if _BAD_CHARS_RE.search(obj):
            snippet = obj[:80].replace("\n", " ")
            violations.append(f"bad characters (em-dash/smart quotes) at {path!r}: {snippet!r}")
    elif isinstance(obj, dict):
        for k, v in obj.items():
            _scan_for_bad_chars(v, f"{path}.{k}" if path else k, violations)
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            _scan_for_bad_chars(item, f"{path}[{i}]", violations)


def _validate_meal_plan(meal_plan: dict, violations: list[str]) -> None:
    """Check that ingredient cal-sums match meal calories within ±2."""
    days = meal_plan.get("days") or []
    if not isinstance(days, list):
        violations.append("mealPlan.days must be a list")
        return

    for day_idx, day in enumerate(days):
        meals = day.get("meals") or []
        if not isinstance(meals, list):
            continue

        for meal_idx, meal in enumerate(meals):
            if not isinstance(meal, dict):
                continue

            meal_cal = meal.get("calories")
            if meal_cal is None:
                continue

            ingredients = meal.get("ingredients") or []
            if not ingredients:
                continue

            ingredient_sum = sum(
                ing.get("cal", 0) for ing in ingredients
                if isinstance(ing, dict)
            )

            if abs(ingredient_sum - meal_cal) > 2:
                meal_name = meal.get("name", f"meal[{meal_idx}]")
                violations.append(
                    f"mealPlan.days[{day_idx}].{meal_name}: "
                    f"ingredient cal sum {ingredient_sum} != meal calories {meal_cal} (tolerance ±2)"
                )
